// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	demo "demoGo/internal/handler/demo"
	"demoGo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getHello",
				Handler: demo.GetHelloHandler(serverCtx),
			},
		},
		rest.WithPrefix("/demo"),
	)
}
