// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package demopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DemoClientClient is the client API for DemoClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoClientClient interface {
	SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
}

type demoClientClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoClientClient(cc grpc.ClientConnInterface) DemoClientClient {
	return &demoClientClient{cc}
}

func (c *demoClientClient) SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, "/demopb.demoClient/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoClientServer is the server API for DemoClient service.
// All implementations must embed UnimplementedDemoClientServer
// for forward compatibility
type DemoClientServer interface {
	SayHello(context.Context, *HelloReq) (*HelloResp, error)
	mustEmbedUnimplementedDemoClientServer()
}

// UnimplementedDemoClientServer must be embedded to have forward compatible implementations.
type UnimplementedDemoClientServer struct {
}

func (UnimplementedDemoClientServer) SayHello(context.Context, *HelloReq) (*HelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDemoClientServer) mustEmbedUnimplementedDemoClientServer() {}

// UnsafeDemoClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoClientServer will
// result in compilation errors.
type UnsafeDemoClientServer interface {
	mustEmbedUnimplementedDemoClientServer()
}

func RegisterDemoClientServer(s grpc.ServiceRegistrar, srv DemoClientServer) {
	s.RegisterService(&DemoClient_ServiceDesc, srv)
}

func _DemoClient_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoClientServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demopb.demoClient/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoClientServer).SayHello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DemoClient_ServiceDesc is the grpc.ServiceDesc for DemoClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demopb.demoClient",
	HandlerType: (*DemoClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _DemoClient_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
